name: Merge from Master to Beta

on:
  workflow_call:
    inputs:
      slackTeamTag:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK:
        required: true
      GH_TOKEN:
        required: true
jobs:
  mergeMasterBeta:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git identity
      run: |
        git config --global user.email "actions@rizzle.com"
        git config --global user.name "actions"

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch entire git history
        token: ${{ secrets.GH_TOKEN }}

    - name: Merge master into beta
      run: |
          git fetch origin master beta
          git checkout beta
          if git merge --no-commit origin/master; then
              echo "Merge successful."
              git commit -m "Merge 'master' into 'beta'" && git push origin beta
          else
              echo "Merge failed or no changes detected. Aborting."
              git merge --abort
              exit 1
          fi

    - name: Send Slack
      if: ${{ failure() }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Merge conflicts occurred when merging master into beta. Please resolve <!subteam^${{ inputs.slackTeamTag }}>.
