name: Serverless Delete Deployment
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCOUNT_ID:
        required: true
      IMAGE:
        required: true

jobs:
  delete-serverless:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Replace Service Name
        run: |
            sed -i 's/service: BACK/service: ${{ inputs.branch }}/g' serverless.yml

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY

      - name: Delete using Serverless Framework
        env:
          BRANCH_NAME: ${{ inputs.branch }}
          ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          IMAGE: ${{ secrets.IMAGE }}
        run: |
          serverless remove --param="account_id=$ACCOUNT_ID" --param="branch_name=$BRANCH_NAME" --param="image=$IMAGE"
